#!/usr/bin/env ruby

require 'pp'
require 'pathname'
require 'fileutils'
require_relative '../lib/osgeo/termbase.rb'
# require 'pry'

filepath = ARGV[0]

if filepath.nil?
  puts 'Error: no filepath given as first argument.'
  exit 1
end

if Pathname.new(filepath).extname != ".csv"
  puts 'Error: filepath given must have extension .csv.'
  exit 1
end

table_config = Osgeo::Termbase::Csv::Config.new(
  header_row_index: 2, term_preferred_column: 1, term_admitted_column: 2,
  term_abbrev_column: 3, definition_column: 4, source_link_column: 11,
  example1_column: 5, example2_column: 7, example3_column: 9,
  note1_column: 6, note2_column: 8, note3_column: 10,
)

concepts = Osgeo::Termbase::Csv.new(filepath, table_config).concepts

# registries = {
#   "eng" => {
#     metadata: {},
#     terms: table.to_concept_collection
#   }
# }

output_dir = Dir.pwd

# metadata = {
#   'header' => workbook.glossary_info.metadata_section.to_hash["metadata"]
# }
# # Write registry metadata
# metadata['languages'] = registries.inject({}) do |acc, (lang, data)|
#   acc.merge({lang => data[:metadata]})
# end

# File.open(File.join(output_dir, Pathname.new(filepath).basename.sub_ext(".meta.yaml")),"w") do |file|
#   file.write(metadata.to_yaml)
# end


# Merge concept arrays
merged_terms = concepts
merged_terms.sort_by! { |t| t.default_designation.downcase }
merged_terms.each.with_index { |t, i| t.id = i + 1 } # Re-calculate ids

collection = Osgeo::Termbase::ConceptCollection.new
merged_terms.each { |t| collection.add_term(t) }

# Aggregated YAML
# collection.to_file(File.join(output_dir, Pathname.new(filepath).basename.sub_ext(".yaml")))

collection_output_dir = File.join(output_dir, "concepts")

FileUtils.mkdir_p(collection_output_dir)

collection.keys.each do |id|
  collection[id].to_file(File.join(collection_output_dir, "concept-#{id}.yaml"))
end
